spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
#  main:
server:
  port: 8081
#    web-application-type: none